instituicao: "Instituto Mauá de Tecnologia (IMT)"
curso: "Sistemas de Informação"
grau: "Bacharelado"
semestre: 7
periodo_inicio: "08/2022"
previsao_formatura: "08/2027"
cidade_campus: "São Caetano do Sul"
estado_campus: "SP"
status: "Cursando"
turno: "Noturno"

horario_disponivel: "Qualquer horário, exceto 19h–22h (aula)"
carga_horaria_semanal: "30h/semana"
disponibilidade_inicio: "Imediata"
