# Copiar para profile.yml e preencher

# Identificação
nome: ""
nome_social: ""
data_nascimento: "" # DD/MM/AAAA
cpf: ""
rg: ""
rg_orgao: ""
nacionalidade: "Brasileira"
sexo: ""
estado_civil: ""
naturalidade_cidade: ""
naturalidade_estado: ""

# Documentos
cnh: ""
cnh_categoria: ""

# Comunicação
email: ""
telefone: ""
whatsapp: ""

# Endereço
cep: ""
logradouro: ""
numero: ""
complemento: ""
bairro: ""
cidade: ""
estado: ""
pais: "Brasil"

# Links
linkedin: ""
github: ""
portfolio: ""

# Diversidade
pcd: "Não"
cor_ou_raca: ""
identidade_genero: ""
orientacao_sexual: ""
pronome: ""
consentimento_diversidade: ""
